src/garage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^admin/', admin.site.urls),
    
    url(r'^our-team/$', TemplateView.as_view(template_name='our_team.html')),
    url(r'^$', TemplateView.as_view(template_name='home_page.html'), name='home'),
    url(r'^vehicles/', include('vehicles.urls', namespace='vehicles')),
    url(r'^parties/', include('vehicles.urls_party', namespace='parties')),
    # url(r'^vehicles/(?P<slug>[\w-]+)/$', vehicle_detailsview, name='details'),
    # url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^contact/$', TemplateView.as_view(template_name='contact.html', name='contact'),

]

src/vehicles/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import (
	vehicles_purchased_listview,
	vehicle_purchased_detailsview,
	vehicle_sold_detailsview,
	vehicle_addview,
	bills_view,
	add_vehilceform_view,
	vehicles_sold_listview,
	invoice_purchase_createview,
	add_vehicle_createview,
	add_party_seller_createview,
	VehicleDetailsUpdate,
	VehicleDelete,
	# PurchaseInvoiceDetailsUpdate,
	GeneratePdfPurchaseInvoice,
	GeneratePdfSalesInvoice,
)

urlpatterns = [
	url(r'^purchased/(?P<slug>[\w-]+)/details/$', vehicle_purchased_detailsview, name='purchased-details'),
	url(r'^sold/(?P<slug>[\w-]+)/print/$', GeneratePdfSalesInvoice.as_view(), name='invoice-sales-print'),
	url(r'^purchased/(?P<slug>[\w-]+)/print/$', GeneratePdfPurchaseInvoice.as_view(), name='invoice-purchase-print'),
	url(r'^purchased/(?P<slug>[\w-]+)/delete/$', VehicleDelete.as_view(), name='vehicle-delete'),
	url(r'^purchased/(?P<slug>[\w-]+)/update/$', VehicleDetailsUpdate.as_view(), name='vehicle-update'),
	url(r'add-vehicle/$', add_vehicle_createview, name='add-vehicle'),
	url(r'purchase-vehicle/$', TemplateView.as_view(template_name='vehicles/purchase_vehicle.html'), name='purchase-vehicle'),
	url(r'add-party/$', add_party_seller_createview, name='add-party'),
	url(r'invoice-purchase/$', invoice_purchase_createview, name='invoice-purchase'),
	url(r'bills/$', bills_view, name='bills'),
	url(r'sold/$', vehicles_sold_listview, name='sold-list'),
	url(r'^sold/(?P<slug>[\w-]+)/details/$', vehicle_sold_detailsview, name='sold-details'),
	url(r'$', vehicles_purchased_listview, name='purchased-list'),

]

src/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class='container'>
<h1>VROOM VROOM Garage</h1>
<a href='{% url "home" %}'>Home</a>
<a href='{% url "about" %}'>About</a>
<a href='{% url "contact" %}'>Contact</a>
<a href='{% url "vehicles:list" %}'>Vehicles</a>
<a href='{% url "vehicles:details" slug="fzs" %}'>FZS</a>
<a href='{% url "vehicles:add" %}'>Add Vehicles</a>
<a href='{% url "vehicles:bills" %}'>Bills</a>
</div>