src/garage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^accounts/', include('accounts.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^admin/', admin.site.urls),
    
    url(r'^our-team/$', TemplateView.as_view(template_name='our_team.html')),
    url(r'^$', TemplateView.as_view(template_name='home_page.html'), name='home'),
    url(r'^vehicles/', include('vehicles.urls', namespace='vehicles')),
    url(r'^parties/', include('vehicles.urls_party', namespace='parties')),
    # url(r'^vehicles/(?P<slug>[\w-]+)/$', vehicle_detailsview, name='details'),
    # url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^contact/$', TemplateView.as_view(template_name='contact.html', name='contact'),

]

src/vehicles/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import (
	vehicles_purchased_listview,
	vehicle_purchased_detailsview,
	vehicle_sold_detailsview,
	vehicle_addview,
	bills_view,
	add_vehilceform_view,
	vehicles_sold_listview,
	invoice_purchase_createview,
	add_vehicle_createview,
	add_party_seller_createview,
	VehicleDetailsUpdate,
	VehicleDelete,
	# PurchaseInvoiceDetailsUpdate,
	GeneratePdfPurchaseInvoice,
	GeneratePdfSalesInvoice,
)

urlpatterns = [
	url(r'^purchased/(?P<slug>[\w-]+)/details/$', vehicle_purchased_detailsview, name='purchased-details'),
	url(r'^sold/(?P<slug>[\w-]+)/print/$', GeneratePdfSalesInvoice.as_view(), name='invoice-sales-print'),
	url(r'^purchased/(?P<slug>[\w-]+)/print/$', GeneratePdfPurchaseInvoice.as_view(), name='invoice-purchase-print'),
	url(r'^purchased/(?P<slug>[\w-]+)/delete/$', VehicleDelete.as_view(), name='vehicle-delete'),
	url(r'^purchased/(?P<slug>[\w-]+)/update/$', VehicleDetailsUpdate.as_view(), name='vehicle-update'),
	url(r'add-vehicle/$', add_vehicle_createview, name='add-vehicle'),
	url(r'purchase-vehicle/$', TemplateView.as_view(template_name='vehicles/purchase_vehicle.html'), name='purchase-vehicle'),
	url(r'add-party/$', add_party_seller_createview, name='add-party'),
	url(r'invoice-purchase/$', invoice_purchase_createview, name='invoice-purchase'),
	url(r'bills/$', bills_view, name='bills'),
	url(r'sold/$', vehicles_sold_listview, name='sold-list'),
	url(r'^sold/(?P<slug>[\w-]+)/details/$', vehicle_sold_detailsview, name='sold-details'),
	url(r'$', vehicles_purchased_listview, name='purchased-list'),

]

src/vehicles/forms.py
from django.forms import ModelForm
from django import forms
from .models import InvoicePurchase, InvoiceSale, PartyDetails, VehicleDetails


class InvoicePurchaseCreateForm(forms.ModelForm):
    class Meta:
        model = InvoicePurchase
        fields = [
                    'amount_purchased',
                    'expense',
                    'valuation_amount',
                    'party_purchased',
                    # 'vehicle_detail',
        ]

class PartyDetailsCreateForm(forms.ModelForm):
    class Meta:
        model = PartyDetails
        fields = [
                    'full_name',
                    'aadhar_no',
                    'phone_no',
                    'email',
                    'address',
                    'vehicle_detail',
                    'is_seller',
        ]


class VehicleDetailsCreateForm(forms.ModelForm):
    class Meta:
        model = VehicleDetails
        fields = [
                    'manufacturer',
                    'model_name',
                    'model_year',
                    'color',
                    'registration_no',
                    'chassis_no',
        ]
# class PartyDetailsForm(forms.ModelForm):
#     email = forms.EmailField(label='Email Address')
#     first_name = forms.CharField(label='First Name')
#     last_name = forms.CharField(label='Last Name')
#     confirm_password = forms.CharField(
#         widget=forms.PasswordInput,
#         label='Confirm Password'
#     )
#     aadhar_no = forms. 
# 	class Meta:
# 		model = PartyDetails
# 		fields = [
# 			'first_name',
# 			'last_name',
# 			'aadhar_no',
# 			'address',
# 			'phone_no',
# 			'email'
# 		]

# 	# def clean_confirm_password(self):
# 	# 	email = self.cleaned_data.get('email')
# 	# 	password = self.cleaned_data.get('password')
# 	# 	confirm_password = self.cleaned_data.get('confirm_password')
# 	# 	if password != confirm_password:
# 	# 		raise forms.ValidationError('Passwords do not match')
# 	# 	check_email = UserDetails.objects.filter(email=email)
# 	# 	if check_email.exists():
# 	# 		raise forms.ValidationError('This email has already been taken')
# 	# 	return email

# class UserRegisterForm(forms.ModelForm):
#     email = forms.EmailField(label='Email Address')
#     first_name = forms.CharField(label='First Name')
#     last_name = forms.CharField(label='Last Name')
#     confirm_password = forms.CharField(
#         widget=forms.PasswordInput,
#         label='Confirm Password'
#     )
#     class Meta:
#         model = User
#         fields = [
#             'first_name',
#             'last_name',
#             'email',
#         ]

#     def clean_confirm_password(self):
#         email = self.cleaned_data.get('email')
#         password = self.cleaned_data.get('password')
#         confirm_password = self.cleaned_data.get('confirm_password')
#         if password != confirm_password:
#             raise forms.ValidationError('Passwords do not match')
#         check_email = User.objects.filter(email=email)
#         if check_email.exists():
#             raise forms.ValidationError('This email has already been taken')
#         return email

src/vehicles/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template

from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView 
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import InvoicePurchaseCreateForm, PartyDetailsCreateForm, VehicleDetailsCreateForm
from .models import InvoicePurchase, InvoiceSale, PartyDetails, VehicleDetails
from .utils import render_to_pdf 



@login_required(login_url='/accounts/login/')
def invoice_purchase_createview(request):
	form = InvoicePurchaseCreateForm(None or request.POST)
	errors = None
	if form.is_valid():
		# obj = InvoicePurchaseCreateForm
		form.date_time = datetime.datetime.today()
		form.save()
		return HttpResponseRedirect('/vehicles/')
	if form.errors:
		errors = form.errors
	
	template_name = 'vehicles/invoice_purchase_create_form.html'
	context = {
				'form': form,
				'errors': errors,
	}
	return render(request, template_name, context)


# class AddVehicleCreateView(LoginRequiredMixin, CreateView):
#     form_class = VehicleDetailsCreateForm
#     login_url = '/accounts/login/'
#     template_name = 'add_vehicle_create_form.html'
#     success_url = reverse_lazy('vehicles:add-party')

#     def form_valid(self, form):
#         instance = form.save(commit=False)
#         # instance.owner = self.request.user
#         return super(VehicleDetailsCreateForm, self).form_valid(form)

#     def get_context_data(self, *args, **kwargs):
#         context = super(VehicleDetailsCreateForm, self).get_context_data(*args, **kwargs)
#         context['title'] = 'Add Vehicle'
#         return context

@login_required(login_url='/accounts/login/')
def add_vehicle_createview(request):
	form = VehicleDetailsCreateForm(None or request.POST)
	errors = None
	if form.is_valid():
		# obj = InvoicePurchaseCreateForm
		print(form)
		form.save()
		return HttpResponseRedirect('/vehicles/add-party/')
	if form.errors:
		errors = form.errors
	
	template_name = 'vehicles/add_vehicle_create_form.html'
	context = {
				'form': form,
				'errors': errors,
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def add_party_seller_createview(request):
	form = PartyDetailsCreateForm(None or request.POST, initial={'is_seller': True})
	errors = None
	if form.is_valid():
		print(form.cleaned_data)
		print(form.is_bound)
		form.cleaned_data['is_seller'] = True
		# obj = InvoicePurchaseCreateForm
		# form.is_seller = True
		print(form.cleaned_data['is_seller'])
		print(form.cleaned_data)
		form.save()
		return HttpResponseRedirect('/vehicles/invoice-purchase/')
	if form.errors:
		errors = form.errors
	
	template_name = 'vehicles/add_seller_create_form.html'
	context = {
				'form': form,
				'errors': errors,
	}
	return render(request, template_name, context)

# Create your views here.
@login_required(login_url='/accounts/login/')
def vehicles_purchased_listview(request):
	# print('hello_sold')
	template_name = 'vehicles/vehicles_list_purchased.html'
	queryset = VehicleDetails.objects.filter(is_sold=False)
	context = {
		"vehicles_list": queryset
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def vehicles_sold_listview(request):
	print('hello')
	template_name = 'vehicles/vehicles_list_sold.html'
	queryset = VehicleDetails.objects.filter(is_sold=True)
	context = {
		"vehicles_list": queryset
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def parties_listview(request):
	template_name = 'parties/parties_list.html'
	queryset = PartyDetails.objects.all()
	context = {
		"parties_list": queryset
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def add_vehilceform_view(request):
    form = (request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        user.set_password(password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        # this is required step before login
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/vehicles/')
    return render(request, 'accounts/register_form.html', {'form': form})


def vehicle_addview(request):
	return HttpResponse('add vehicles')


def bills_view(request):
	return HttpResponse('bills listed here')


@login_required(login_url='/accounts/login/')
def vehicle_purchased_detailsview(request, **kwargs):
	slug = kwargs.get('slug')
	template_name = 'vehicles/vehicle_details.html'
	# slug = get_object_or_404(VehicleDetails, slug)
	queryset = VehicleDetails.objects.get(slug=slug)
	party_details = PartyDetails.objects.get(vehicle_detail_id=queryset.id)
	bill_p = InvoicePurchase.objects.get(party_purchased_id=party_details.id)
	context = {
		"vehicle": queryset,
		"bill_p": bill_p,
	}
	return render(request, template_name, context)


def vehicle_sold_detailsview(request, **kwargs):
	slug = kwargs.get('slug')
	template_name = 'vehicles/vehicle_details.html'
	# slug = get_object_or_404(VehicleDetails, slug)
	queryset = VehicleDetails.objects.get(slug=slug)
	party_details = PartyDetails.objects.filter(is_seller=True).get(vehicle_detail_id=queryset.id)
	bill_p = InvoicePurchase.objects.get(party_purchased_id=party_details.id)
	bill_s = InvoiceSale.objects.get(purchase_bill_no_id=bill_p.id)
	context = {
		"vehicle": queryset,
		"bill_p": bill_p,
		"bill_s": bill_s,
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def party_seller_detailsview(request, **kwargs):
	slug = kwargs.get('slug')
	template_name = 'parties/party_details.html'
	# slug = get_object_or_404(VehicleDetails, slug)
	queryset = PartyDetails.objects.get(slug=slug)
	bill = InvoicePurchase.objects.get(party_purchased_id=queryset.id)
	context = {
		"party": queryset,
		"bill": bill,
	}
	return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def party_buyer_detailsview(request, **kwargs):
	slug = kwargs.get('slug')
	template_name = 'parties/party_details.html'
	# slug = get_object_or_404(VehicleDetails, slug)
	queryset = PartyDetails.objects.get(slug=slug)
	bill = InvoiceSale.objects.get(party_sold_id=queryset.id)
	context = {
		"party": queryset,
		"bill": bill,
	}
	return render(request, template_name, context)


class VehicleDetailsUpdate(UpdateView):
    model = VehicleDetails
    template_name = 'vehicles/update_vehicle_form.html'
    fields = ['manufacturer',
    		  'model_name',
    		  'model_year',
    		  'color',
    		  'registration_no',
    		  'chassis_no',
    		]
    success_url = reverse_lazy('vehicles:purchased-list')


class VehicleDelete(DeleteView):
    model = VehicleDetails
    success_url = reverse_lazy('vehicles:purchased-list')


class SellerDetailsUpdate(UpdateView):
	model = PartyDetails
	template_name = 'vehicles/update_seller_form.html'
	fields = [
				'full_name',
				'aadhar_no',
				'phone_no',
				'email',
				'address',
				'vehicle_detail',
				'is_seller',
				]
	success_url = reverse_lazy('parties:list')


# class PurchaseInvoiceDetailsUpdate(UpdateView):
# 	model = InvoicePurchase
# 	success_url = reverse_lazy('vehicles:purchased-list')
# 	fields = [
# 				'amount_purchased',
# 				'expense',
# 				'valuation_amount',
# 				'party_purchased',
# 				# 'vehicle_detail',
				
# 			]
#     # success_url = reverse_lazy('')  
# 	def get_queryset(self):
		# slug = self.kwargs.get("slug")
# 		queryset = VehicleDetails.objects.get(slug=slug)
# 		party_details = PartyDetails.objects.get(vehicle_detail_id=queryset.id)
# 		# bill_p = InvoicePurchase.objects.get(party_purchased_id=party_details.id)
# 		return InvoicePurchase.objects.get(party_purchased_id=party_details.id)

# def update_vehicle_purchased_detailsview(request, **kwargs):
# 	slug = kwargs.get('slug')
# 	template_name = 'vehicles/vehicle_details.html'
# 	# slug = get_object_or_404(VehicleDetails, slug)
# 	queryset = VehicleDetails.objects.get(slug=slug)
# 	party_details = PartyDetails.objects.get(vehicle_detail_id=queryset.id)
# 	bill_p = InvoicePurchase.objects.get(party_purchased_id=party_details.id)
# 	context = {
# 		"vehicle": queryset,
# 		"bill_p": bill_p,
# 	}
# 	return render(request, template_name, context)



class GeneratePdfPurchaseInvoice(View):
	def get(self, request, *args, **kwargs):
		slug = kwargs.get('slug')
		template = get_template('pdf/purchase_invoice.html')
		queryset = VehicleDetails.objects.get(slug=slug)
		party_details = PartyDetails.objects.get(vehicle_detail_id=queryset.id)
		bill_p = InvoicePurchase.objects.get(party_purchased_id=party_details.id)
		context = {
				'seller_full_name': bill_p.party_purchased.full_name,
				'seller_phone_no': bill_p.party_purchased.phone_no,
				'seller_email': bill_p.party_purchased.email,
				'seller_address': bill_p.party_purchased.address,
				'seller_aadhar_no': bill_p.party_purchased.aadhar_no,
				'vehicle_manufacturer': bill_p.party_purchased.vehicle_detail.manufacturer,
				'vehicle_model_name': bill_p.party_purchased.vehicle_detail.model_name,
				'vehicle_model_year': bill_p.party_purchased.vehicle_detail.model_year,
				'vehicle_color': bill_p.party_purchased.vehicle_detail.color,
				'vehicle_registration_no': bill_p.party_purchased.vehicle_detail.registration_no,
				'vehicle_chassis_no': bill_p.party_purchased.vehicle_detail.chassis_no,
				'invoice_no': bill_p.bill_no,
				'amount_purchased': bill_p.amount_purchased,
				'date_time': bill_p.date_time,

src/vehicles/templates/vehicles/add_seller_create_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Add Seller||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Add Seller</h1>

<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/add_vehicle_create_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Add Vehicle||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Add Vehicle</h1>
<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/add_vehicle_form.html
{% extends "base.html" %}

{% block content %}
    {% load staticfiles %}
    {% load crispy_forms_tags %}
        <div class="col-md-6 col-md-offset-3">
            <legend>
                <h1>Add Vehicle</h1>
            </legend>
            <form method="POST" action="" style="margin-top:3%">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn tbn-default" />
            </form>
        </div>
{% endblock %}

src/vehicles/templates/vehicles/invoice_purchase_create_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Purchase Invoice||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Purchase Invoice</h1>

<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/purchase_vehicle.html
{% extends 'base.html' %}
{% block head_title %}Purchase Vehicle||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<a href="{% url 'vehicles:add-vehicle' %}">
	<h2>
		Add Vehicle
	</h2>
</a><br>
</li>
<a href="{% url 'vehicles:add-party' %}">
	<h2>
		Add Seller
	</h2>
</a><br/>
<a href="{% url 'vehicles:invoice-purchase' %}">
	<h2>
		Generate Invoice
	</h2>
</a><br/>
{% endblock %}

src/vehicles/templates/vehicles/text_centre_css.html
<div style="
    display: inline-block;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    width: 200px;
    height: 100px;
    margin: auto;
    background-color: #f3f3f3;">Full Center ON Page
</div>

src/vehicles/templates/vehicles/update_invoice_purchase_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Purchase Invoice||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Update Purchase Invoice</h1>

<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/update_seller_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Add Seller||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Update Seller Details</h1>

<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/update_vehicle_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block head_title %}Add Vehicle||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Update Vehicle Details</h1>
<form  method="POST"> {% csrf_token %}
	{{ form|crispy }}
	<button type="Submit">Save</button>	
</form>
{% endblock %}

src/vehicles/templates/vehicles/vehicle_details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load mathfilters %}
{% block head_title %}Vehicles||{{ block.super }}{% endblock head_title %}
{% block content %}
<h1>
	{{ vehicle.model_name }}
</h1>
<h3>
	{{ vehicle.manufacturer }}
</h3>
<p>
	model year -> {{ vehicle.model_year }}
</p>
<p>
	registration no -> {{ vehicle.registration_no }}
</p>
<p>
	color -> {{ vehicle.color }}
</p>
<p>
	<h3>
		purchased from 
		<a href="{% url 'parties:seller-details' slug=bill_p.party_purchased.slug %}">
			{{ bill_p.party_purchased.full_name }}
		</a><br/>
		<h4>
			at
		</h4>
		<h3>
			Rs. {{ bill_p.amount_purchased}}
		</h3>
	</h3>
	<h4>
		expense :- Rs. {{ bill_p.expense }}

	</h4>
	<br>
	<h3>
		<strong>
			To be sold at
			Rs. {{ bill_p.valuation_amount}}
		</strong>
	</h3>

</p>
{% if vehicle.is_sold %}
	<h1>
		AND
	</h1>
    <p>
    	<h3>
		sold to 
		<a href="{% url 'parties:buyer-details' slug=bill_s.party_sold.slug %}">
			{{ bill_s.party_sold.full_name }}
		</a><br/>
		<h4>
			at
		</h4>
		<h3>
			Rs. {{ bill_s.amount_sold}}
		</h3>
		<h2>
			Net Profit:- {{ bill_s.amount_sold|sub:bill_p.amount_purchased|sub:bill_p.expense}}
		</h2>
	</h3>
	
	</p>
	<h4><center>
	<a href="{% url 'vehicles:invoice-sales-print' vehicle.slug  %}">
    <button type="submit" class="btn btn-default btn-sm">
    	Print Sales Invoice
    </button>
	</a>
    </form>
    </center>
</h4>

{% endif %}
{% if not vehicle.is_sold %}
<h4><center>
	<form action="{% url 'vehicles:vehicle-update' vehicle.slug  %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-default btn-sm">
    	Update Vehicle Details
    </button>
    </form>
    </center>
</h4>
<h4><center>
	<form action="{% url 'vehicles:vehicle-delete' vehicle.slug %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-sm">
            Delete Vehicle from Garage
        </button>
    </form>
    </center>
           
</h4>
<h4>
	<center>
	<a href="{% url 'vehicles:invoice-purchase-print' vehicle.slug  %}">
    <button type="submit" class="btn btn-default btn-sm">
    	Print Invoice
    </button>
	</a>
    </form>
    </center>
</h4>
{% comment %}
<h4>
	<a href="{% url 'vehicles:invoice-purchase-download' vehicle.slug  %}">
    <button type="submit" class="btn btn-default btn-sm">
    	Download Invoice
    </button>
	</a>
    </form>
</h4>
<h4>
	<form action="{% url 'vehicles:invoice-purchase-update' vehicle.slug  %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-default btn-sm">
    	Update Accounts
    </button>
    </form>
</h4>
{% endcomment %}
{% endif %}
{% endblock %}

src/vehicles/templates/vehicles/vehicles_list_purchased.html
{% extends 'base.html' %}
{% block head_title %}Vehicles||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Vehicles Present in Garage</h1>
<ul>
	{% for vehicle in vehicles_list %}
	<li>
		<a href="{% url 'vehicles:purchased-details' slug=vehicle.slug %}">{{ vehicle }}
		</a><br/>
		{{ vehicle.registration_no }} {{ vehicle.timestamp }}
		<a href="http://127.0.0.1:8000/admin/vehicles/invoicesale/add/">
			Sell Vehicle
		</a><br/>
	</li>
{% endfor %}
</ul>
{% endblock %}

src/vehicles/templates/vehicles/vehicles_list_sold.html
{% extends 'base.html' %}
{% block head_title %}Vehicles||{{ block.super }}{% endblock head_title %}
{% block content %}
<br>
<h1>Sold Vehicles</h1>
<ul>
	{% for vehicle in vehicles_list %}
	<li>
		<a href="{% url 'vehicles:sold-details' slug=vehicle.slug %}">{{ vehicle }}
		</a><br/>
		{{ vehicle.registration_no }} {{ vehicle.timestamp }}
	</li>
{% endfor %}
</ul>
{% endblock %}